"""
Relational Database Models
SQLAlchemy ORM schemas for users, cases, audit logs, and entity merges
"""

from datetime import datetime, timezone
import json
from sqlalchemy import Column, Integer, String, Text, DateTime, Float, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from backend.app.database.connection import Base

class User(Base):
    """User account model supporting Role-Based Access Control (RBAC)."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(64), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    full_name = Column(String(128), nullable=False)
    role = Column(String(32), nullable=False, default="Investigating Officer")
    badge_number = Column(String(64), nullable=True)
    jurisdiction_code = Column(String(64), nullable=False, default="DL-POLICE-SPL")
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    def to_dict(self):
        return {
            "id": self.id,
            "username": self.username,
            "full_name": self.full_name,
            "role": self.role,
            "badge_number": self.badge_number,
            "jurisdiction_code": self.jurisdiction_code,
            "is_active": self.is_active,
            "created_at": self.created_at.isoformat() if self.created_at else None
        }


class CaseRecord(Base):
    """FIR / Police Case Record storing structured metadata and raw narrative."""
    __tablename__ = "cases"

    id = Column(Integer, primary_key=True, index=True)
    case_id = Column(String(64), unique=True, index=True, nullable=False)
    fir_number = Column(String(64), unique=True, index=True, nullable=False)
    station = Column(String(128), nullable=False)
    jurisdiction_code = Column(String(64), nullable=False)
    state = Column(String(64), nullable=False)
    crime_category = Column(String(128), nullable=False)
    filed_date = Column(String(32), nullable=False)
    investigating_officer = Column(String(128), nullable=False)
    status = Column(String(32), default="Under Investigation")
    narrative_text = Column(Text, nullable=False)
    extracted_entities_json = Column(Text, default="{}")
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    def to_dict(self):
        return {
            "id": self.id,
            "case_id": self.case_id,
            "fir_number": self.fir_number,
            "station": self.station,
            "jurisdiction_code": self.jurisdiction_code,
            "state": self.state,
            "crime_category": self.crime_category,
            "filed_date": self.filed_date,
            "investigating_officer": self.investigating_officer,
            "status": self.status,
            "narrative_text": self.narrative_text,
            "extracted_entities": json.loads(self.extracted_entities_json or "{}"),
            "created_at": self.created_at.isoformat() if self.created_at else None
        }


class AuditLog(Base):
    """
    Cryptographically chained, tamper-evident audit log model.
    Every query, search, view, export, and merge is chained via SHA-256 hashing.
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    sequence_id = Column(Integer, index=True, nullable=False)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    user_id = Column(Integer, nullable=True)
    username = Column(String(64), nullable=False)
    user_role = Column(String(32), nullable=False)
    ip_address = Column(String(64), default="127.0.0.1")
    action = Column(String(64), nullable=False)  # e.g., "SEARCH", "VIEW_DOSSIER", "CASE_INTAKE", "EXPORT_REPORT"
    entity_type = Column(String(32), nullable=True)  # e.g., "Person", "Case", "Graph"
    entity_id = Column(String(128), nullable=True)
    details_json = Column(Text, default="{}")
    prev_hash = Column(String(64), nullable=False)
    current_hash = Column(String(64), nullable=False, unique=True, index=True)

    def to_dict(self):
        return {
            "id": self.id,
            "sequence_id": self.sequence_id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "user_id": self.user_id,
            "username": self.username,
            "user_role": self.user_role,
            "ip_address": self.ip_address,
            "action": self.action,
            "entity_type": self.entity_type,
            "entity_id": self.entity_id,
            "details": json.loads(self.details_json or "{}"),
            "prev_hash": self.prev_hash,
            "current_hash": self.current_hash
        }


class EntityMergeCandidate(Base):
    """Suggestions generated by the Entity Resolution Engine for human confirmation."""
    __tablename__ = "entity_merge_candidates"

    id = Column(Integer, primary_key=True, index=True)
    entity_type = Column(String(32), nullable=False)
    primary_id = Column(String(128), nullable=False)
    primary_name = Column(String(128), nullable=False)
    candidate_id = Column(String(128), nullable=False)
    candidate_name = Column(String(128), nullable=False)
    similarity_score = Column(Float, nullable=False)
    match_reasons_json = Column(Text, default="[]")
    status = Column(String(32), default="PENDING")  # PENDING, APPROVED, REJECTED
    suggested_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    reviewed_by = Column(String(64), nullable=True)
    reviewed_at = Column(DateTime, nullable=True)

    def to_dict(self):
        return {
            "id": self.id,
            "entity_type": self.entity_type,
            "primary_id": self.primary_id,
            "primary_name": self.primary_name,
            "candidate_id": self.candidate_id,
            "candidate_name": self.candidate_name,
            "similarity_score": self.similarity_score,
            "match_reasons": json.loads(self.match_reasons_json or "[]"),
            "status": self.status,
            "suggested_at": self.suggested_at.isoformat() if self.suggested_at else None,
            "reviewed_by": self.reviewed_by,
            "reviewed_at": self.reviewed_at.isoformat() if self.reviewed_at else None
        }
